FROM node:20-alpine as install-base
WORKDIR /var/task
ENV SLY_DEBUG="true"

FROM node:20-alpine as install-api1
WORKDIR /var/task
ENV SLY_DEBUG="true"
COPY api1 /var/task/api1
COPY package.json /var/task/package.json
RUN cd api1 && npm install

FROM node:20-alpine as install-2
WORKDIR /var/task
ENV SLY_DEBUG="true"

FROM install-base as build-base
WORKDIR /var/task
ENV PATH="/var/task:$PATH"
ENV SLY_DEBUG="true"
COPY . /var/task/

FROM install-api1 as build-api1
WORKDIR /var/task
ENV PATH="/var/task/api1:$PATH"
ENV SLY_DEBUG="true"
COPY api1 /var/task/api1
COPY package.json /var/task/package.json

FROM install-2 as build-2
WORKDIR /var/task
ENV PATH="/var/task/api2:$PATH"
ENV SLY_DEBUG="true"
COPY api2 /var/task/api2
COPY package.json /var/task/package.json
COPY --from=build-api1 /var/task/node_modules /var/task/node_modules

FROM install-base as package-base
WORKDIR /var/task
ENV PATH="/var/task:$PATH"
ENV SLY_DEBUG="true"

FROM install-api1 as package-api1
WORKDIR /var/task
ENV PATH="/var/task/api1:$PATH"
ENV SLY_DEBUG="true"
COPY --from=build-api1 /var/task/package.json /var/task/package.json
COPY --from=build-api1 /var/task/api1* /var/task/api1

FROM install-2 as package-2
WORKDIR /var/task
ENV PATH="/var/task/api2:$PATH"
ENV SLY_DEBUG="true"
COPY --from=build-2 /var/task/package.json /var/task/package.json
COPY --from=package-api1 /var/task/node_modules /var/task/node_modules
COPY --from=build-2 /var/task/api2* /var/task/api2

FROM install-base as runtime
WORKDIR /var/task
ENV PATH="/var/task:$PATH"
ENV PATH="/var/task/api2:$PATH"
ENV PATH="/var/task/api1:$PATH"
ENV SLY_DEBUG="true"
COPY .entrypoint* /var/task/.entrypoint
COPY --from=package-2 /var/task/package.json /var/task/package.json
COPY --from=package-2 /var/task/node_modules /var/task/node_modules
COPY --from=package-2 /var/task/api2/* /var/task/api2/
COPY --from=package-api1 /var/task/package.json /var/task/package.json
COPY --from=package-api1 /var/task/api1/* /var/task/api1/
CMD ( cd api1 && node index.cjs ) & ( cd api2 && node index.cjs )