ame: Scaffoldly GitHub Action
description: Deploy a Scaffoldly Application
branding:
  icon: 'arrow-up-circle'
  color: 'gray-dark'
inputs:
  operation:
    description: The operation to perform (deploy)
    required: true
    default: 'deploy'
  github-token:
    description: The GitHub Token to use for deployment
    required: false
    default: ${{ github.token }}
  working-directory:
    description: The working directory to deploy from
    required: false
    default: '.'
  aws-role:
    description: The AWS Role to use for deployment
    required: true
  aws-region:
    description: The AWS Region to deploy to
    required: true
    default: 'us-east-1'
outputs:
  origin:
    description: The URL of the deployed application
  stage:
    description: The inferred stage from the branch or PR name
  deployed:
    description: If the stack was deployed.
  destroyed:
    description: If the stack was destroyed.
runs:
  using: 'node20'
  pre: scripts/github-action-pre.cjs
  main: scripts/github-action-main.cjs
  post: scripts/github-action-post.cjs
