name: Scaffoldly
description: Build, Test, and Deploy an application with Scaffoldly
branding:
  icon: upload-cloud
  color: gray-dark
inputs:
  operation:
    description: The operation to perform (deploy)
    required: true
    default: 'deploy'
  github-token:
    description: The GitHub Token to use for deployment
    required: false
    default: ${{ github.token }}
  working-directory:
    description: The working directory from which to deploy
    required: false
    default: '.'
  secrets:
    description: Secrets to pass to the deployment, in JSON form. See https://scaffoldly.dev/docs/gha#secrets
    required: false
    default: '{}'
outputs:
  url:
    description: The URL of the deployed application.
  identity:
    description: The identity of the deployed application
runs:
  using: 'node20'
  pre: scripts/github-action-pre.cjs
  main: scripts/github-action-main.cjs
  post: scripts/github-action-post.cjs
