name: Scaffoldly
description: Build, Test, and Deploy an application with Scaffoldly
branding:
  icon: upload-cloud
  color: gray-dark
inputs:
  operation:
    description: The operation to perform (deploy)
    required: true
    default: 'deploy'
  github-token:
    description: The GitHub Token to use for deployment
    required: false
    default: ${{ github.token }}
  working-directory:
    description: The working directory from which to deploy
    required: false
    default: '.'
  secrets:
    description: The secrets to use for deployment. (Use `${{ secrets }}` to pass all secrets, see https://scaffoldly.dev/docs/gha#secrets)
    required: false
outputs:
  origin:
    description: The URL of the deployed application
  stage:
    description: The inferred stage from the branch or PR name
  deployed:
    description: If the stack was deployed.
  destroyed:
    description: If the stack was destroyed.
runs:
  using: 'node20'
  pre: scripts/github-action-pre.cjs
  main: scripts/github-action-main.cjs
  post: scripts/github-action-post.cjs
