FROM node:20-alpine as base

FROM base as build
WORKDIR /var/task
ENV PATH="/var/task/node_modules/.bin:$PATH"
ENV PATH="/var/task:$PATH"
ENV CONFIG="scaffoldly@1.0.12-0:7SERJgBsCkBpW8fy5H9pwVhpZmUKoz8QjFhsSsgYocWR9f7tvgAjiXaeEgw7bm2ffVpgnZ8DwZGAgKRQwaiiKxpBppDWn5GAunMdxkaQ7bBakPRHKGvcc4kf7nmEk7ecZXVq9CkZd9r13btz9ic8spjrvSTaD3FusL5gRuxz4RwaCmXyffteMDhhzF8VB392FeHvr23xX7HpQvaEtb88ysw6G7oi1RwHYjoCt9rifP5aZQRPNhfCuzuGUrapvtmQDvy9YxQQC6iJEmubEENTBsVtnZmVWfwkbKpaDrDHs6dpkpKyUQLaG"
ENV NODE_ENV="production"
ENV HOSTNAME="0.0.0.0"
ENV SLY_DEBUG="true"
COPY . /var/task/
COPY README.md /var/task/README.md
COPY public /var/task/public
COPY node_modules /var/task/node_modules
RUN next build

FROM base as package
ENTRYPOINT ["/var/task/serve","/var/task/entrypoint"]
WORKDIR /var/task
ENV PATH="/var/task/node_modules/.bin:$PATH"
ENV PATH="/var/task:$PATH"
ENV SERVE_CMD="next start"
ENV CONFIG="scaffoldly@1.0.12-0:7SERJgBsCkBpW8fy5H9pwVhpZmUKoz8QjFhsSsgYocWR9f7tvgAjiXaeEgw7bm2ffVpgnZ8DwZGAgKRQwaiiKxpBppDWn5GAunMdxkaQ7bBakPRHKGvcc4kf7nmEk7ecZXVq9CkZd9r13btz9ic8spjrvSTaD3FusL5gRuxz4RwaCmXyffteMDhhzF8VB392FeHvr23xX7HpQvaEtb88ysw6G7oi1RwHYjoCt9rifP5aZQRPNhfCuzuGUrapvtmQDvy9YxQQC6iJEmubEENTBsVtnZmVWfwkbKpaDrDHs6dpkpKyUQLaG"
ENV NODE_ENV="production"
ENV HOSTNAME="0.0.0.0"
ENV SLY_DEBUG="true"
COPY serve* /var/task/serve
COPY entrypoint* /var/task/entrypoint
COPY --from=build /var/task/README.md /var/task/README.md
COPY --from=build /var/task/LICENSE* /var/task/LICENSE
COPY --from=build /var/task/.next* /var/task/.next
COPY --from=build /var/task/public /var/task/public
COPY --from=build /var/task/node_modules /var/task/node_modules