FROM node:20-alpine as install-0
WORKDIR /var/task

FROM install-0 as build-0
WORKDIR /var/task
ENV PATH="/var/task:$PATH"
ENV PATH="/var/task/node_modules/.bin:$PATH"
COPY . /var/task/
RUN next build

FROM build-0 as package-0
WORKDIR /var/task
ENV PATH="/var/task:$PATH"
ENV PATH="/var/task/node_modules/.bin:$PATH"
COPY --from=build-0 /var/task/.next* /var/task/.next
COPY --from=build-0 /var/task/public /var/task/public
COPY --from=build-0 /var/task/node_modules /var/task/node_modules

FROM install-0 as runtime
WORKDIR /var/task
ENV PATH="/var/task:$PATH"
ENV PATH="/var/task/node_modules/.bin:$PATH"
COPY .entrypoint* /var/task/.entrypoint
COPY --from=package-0 /var/task/.next /var/task/.next
COPY --from=package-0 /var/task/public /var/task/public
COPY --from=package-0 /var/task/node_modules /var/task/node_modules
CMD ( next start )