FROM alpine:3 as install-base
WORKDIR /var/task
ENV SLY_DEBUG="true"
RUN apk update && apk add --no-cache npm && rm -rf /var/cache/apk/*
RUN npm install -g serve@14 --omit=dev --omit=optional --omit=peer && npm cache clean --force

FROM node:22-alpine as install-next
WORKDIR /var/task
ENV SLY_DEBUG="true"
COPY . /var/task/
RUN npm install

FROM install-base as build-base
WORKDIR /var/task
ENV PATH="/var/task:$PATH"
ENV PATH="/var/task/node_modules/.bin:$PATH"
ENV SLY_DEBUG="true"
COPY . /var/task/

FROM install-next as build-next
WORKDIR /var/task
ENV PATH="/var/task:$PATH"
ENV PATH="/var/task/node_modules/.bin:$PATH"
ENV SLY_DEBUG="true"
COPY . /var/task/
RUN next build

FROM install-base as package-base
WORKDIR /var/task
ENV PATH="/var/task:$PATH"
ENV PATH="/var/task/node_modules/.bin:$PATH"
ENV SLY_DEBUG="true"

FROM install-next as package-next
WORKDIR /var/task
ENV PATH="/var/task:$PATH"
ENV PATH="/var/task/node_modules/.bin:$PATH"
ENV SLY_DEBUG="true"
COPY --from=build-next /var/task/package.json /var/task/package.json
COPY --from=build-next /var/task/out* /var/task/out

FROM install-base as runtime
WORKDIR /var/task
ENV PATH="/var/task:$PATH"
ENV PATH="/var/task/node_modules/.bin:$PATH"
ENV SLY_DEBUG="true"
COPY .entrypoint* /var/task/.entrypoint
COPY --from=package-next /var/task/package.json /var/task/package.json
COPY --from=package-next /var/task/out /var/task/out
CMD ( serve out )