FROM node:20-alpine as base-0

FROM base-0 as build-0
WORKDIR /var/task
ENV PATH="/var/task:$PATH"
ENV PATH="/var/task/node_modules/.bin:$PATH"
ENV NODE_ENV="production"
ENV HOSTNAME="0.0.0.0"
ENV SLY_DEBUG="true"
COPY node_modules /var/task/node_modules
COPY . /var/task/
RUN echo 'TODO'

FROM base-0 as package-0
WORKDIR /var/task
ENV PATH="/var/task:$PATH"
ENV PATH="/var/task/node_modules/.bin:$PATH"
ENV NODE_ENV="production"
ENV HOSTNAME="0.0.0.0"
ENV SLY_DEBUG="true"
COPY --from=build-0 /var/task/src* /var/task/src
COPY --from=build-0 /var/task/node_modules /var/task/node_modules

FROM base-0
WORKDIR /var/task
ENV PATH="/var/task:$PATH"
ENV PATH="/var/task/node_modules/.bin:$PATH"
ENV NODE_ENV="production"
ENV HOSTNAME="0.0.0.0"
ENV SLY_DEBUG="true"
COPY .serve* /var/task/.serve
COPY .entrypoint* /var/task/.entrypoint
COPY --from=package-0 /var/task/node_modules /var/task/node_modules
COPY --from=package-0 /var/task/src/* /var/task/
CMD ( node index.cjs )