FROM node:20-alpine as install-base
WORKDIR /var/task
ENV SLY_DEBUG="true"

FROM install-base as build-base
WORKDIR /var/task
ENV PATH="/var/task:$PATH"
ENV PATH="/var/task/node_modules/.bin:$PATH"
ENV SLY_DEBUG="true"
COPY . /var/task/
RUN echo 'TODO'

FROM install-base as package-base
WORKDIR /var/task
ENV PATH="/var/task:$PATH"
ENV PATH="/var/task/node_modules/.bin:$PATH"
ENV PATH="/var/task/src:$PATH"
ENV SLY_DEBUG="true"
COPY --from=build-base /var/task/node_modules /var/task/node_modules
COPY --from=build-base /var/task/src* /var/task/src

FROM install-base as runtime
WORKDIR /var/task
ENV PATH="/var/task:$PATH"
ENV PATH="/var/task/node_modules/.bin:$PATH"
ENV PATH="/var/task/src:$PATH"
ENV SLY_DEBUG="true"
COPY .entrypoint* /var/task/.entrypoint
COPY --from=package-base /var/task/node_modules /var/task/node_modules
COPY --from=package-base /var/task/src/* /var/task/
CMD ( node index.cjs )