FROM alpine:3 as install-0
WORKDIR /var/task
ENV SLY_DEBUG="true"
RUN apk update && apk add --no-cache nginx nodejs && rm -rf /var/cache/apk/*

FROM install-0 as build-0
WORKDIR /var/task
ENV PATH="/var/task:$PATH"
ENV SLY_DEBUG="true"
COPY . /var/task/
RUN echo 'TODO'

FROM build-0 as package-0
WORKDIR /var/task
ENV PATH="/var/task:$PATH"
ENV SLY_DEBUG="true"
COPY --from=build-0 /var/task/nginx /var/task/nginx
COPY --from=build-0 /var/task/html /var/task/html

FROM install-0 as runtime
WORKDIR /var/task
ENV PATH="/var/task:$PATH"
ENV SLY_DEBUG="true"
COPY .entrypoint* /var/task/.entrypoint
COPY --from=package-0 /var/task/nginx /var/task/nginx
COPY --from=package-0 /var/task/html /var/task/html
CMD ( nginx -c /var/task/nginx/nginx.conf )