FROM node:20-alpine as install-base
WORKDIR /var/task
ENV SLY_DEBUG="true"

FROM install-base as build-base
WORKDIR /var/task
ENV PATH="/var/task:$PATH"
ENV PATH="/var/task/node_modules/.bin:$PATH"
ENV SLY_DEBUG="true"
COPY . /var/task/
RUN next build

FROM install-base as package-base
WORKDIR /var/task
ENV PATH="/var/task:$PATH"
ENV PATH="/var/task/node_modules/.bin:$PATH"
ENV SLY_DEBUG="true"
COPY --from=build-base /var/task/out* /var/task/out
COPY --from=build-base /var/task/node_modules /var/task/node_modules

FROM install-base as runtime
WORKDIR /var/task
ENV PATH="/var/task:$PATH"
ENV PATH="/var/task/node_modules/.bin:$PATH"
ENV SLY_DEBUG="true"
COPY .entrypoint* /var/task/.entrypoint
COPY --from=package-base /var/task/out /var/task/out
COPY --from=package-base /var/task/node_modules /var/task/node_modules
CMD ( serve out )