FROM node:20-alpine as install-0
WORKDIR /var/task
ENV SLY_DEBUG="true"

FROM install-0 as build-0
WORKDIR /var/task
ENV PATH="/var/task:$PATH"
ENV PATH="/var/task/node_modules/.bin:$PATH"
ENV SLY_DEBUG="true"
COPY . /var/task/
RUN next build

FROM install-0 as package-0
WORKDIR /var/task
ENV PATH="/var/task:$PATH"
ENV PATH="/var/task/node_modules/.bin:$PATH"
ENV SLY_DEBUG="true"
COPY --from=build-0 /var/task/out* /var/task/out
COPY --from=build-0 /var/task/node_modules /var/task/node_modules

FROM install-0 as runtime
WORKDIR /var/task
ENV PATH="/var/task:$PATH"
ENV PATH="/var/task/node_modules/.bin:$PATH"
ENV SLY_DEBUG="true"
COPY .entrypoint* /var/task/.entrypoint
COPY --from=package-0 /var/task/out /var/task/out
COPY --from=package-0 /var/task/node_modules /var/task/node_modules
CMD ( serve out )